"""Environment-backed local runtime budgets.

The application keeps finite defaults for predictable local operation, but
self-hosted deployments can raise or lower each budget without editing source.
A malformed value falls back to the documented default.
"""

from __future__ import annotations

import os


def env_limit(name: str, fallback: int) -> int:
    raw = os.environ.get(name, "")
    try:
        value = int(raw)
    except (TypeError, ValueError):
        return fallback
    return value if value > 0 else fallback


WORKFLOW_MAX_NODES = env_limit("RR_WORKFLOW_MAX_NODES", 100)
WORKFLOW_MAX_CONNECTIONS = env_limit("RR_WORKFLOW_MAX_CONNECTIONS", 300)
WORKFLOW_MAX_EVENT_LOG = env_limit("RR_WORKFLOW_MAX_EVENT_LOG", 250)
WORKFLOW_MAX_RESULT_BYTES = env_limit("RR_WORKFLOW_MAX_RESULT_BYTES", 1_000_000)
WORKFLOW_MAX_REPEATER_ITEMS = env_limit("RR_WORKFLOW_MAX_REPEATER_ITEMS", 100)
WORKFLOW_MAX_NODE_ID_LENGTH = env_limit("RR_WORKFLOW_MAX_NODE_ID_LENGTH", 120)
WORKFLOW_MAX_DELAY_SECONDS = env_limit("RR_WORKFLOW_MAX_DELAY_SECONDS", 300)
WORKFLOW_MAX_TOOL_POLL_SECONDS = env_limit("RR_WORKFLOW_MAX_TOOL_POLL_SECONDS", 900)
WORKFLOW_EVENT_QUEUE_SIZE = env_limit("RR_WORKFLOW_EVENT_QUEUE_SIZE", 100)
WORKFLOW_EVENT_MESSAGE_LENGTH = env_limit("RR_WORKFLOW_EVENT_MESSAGE_LENGTH", 1000)

BURST_MAX_ITERATIONS = env_limit("RR_BURST_MAX_ITERATIONS", 20)
BURST_MAX_CONCURRENCY = env_limit("RR_BURST_MAX_CONCURRENCY", 4)
BURST_MAX_DELAY_MS = env_limit("RR_BURST_MAX_DELAY_MS", 5000)
BURST_MAX_TIMEOUT_MS = env_limit("RR_BURST_MAX_TIMEOUT_MS", 15000)

LAST_BYTE_MAX_ITERATIONS = env_limit("RR_LAST_BYTE_MAX_ITERATIONS", 20)
LAST_BYTE_MAX_CONCURRENCY = env_limit("RR_LAST_BYTE_MAX_CONCURRENCY", 4)
LAST_BYTE_MAX_DELAY_MS = env_limit("RR_LAST_BYTE_MAX_DELAY_MS", 5000)
LAST_BYTE_MAX_HOLD_MS = env_limit("RR_LAST_BYTE_MAX_HOLD_MS", 2000)
LAST_BYTE_MAX_TIMEOUT_MS = env_limit("RR_LAST_BYTE_MAX_TIMEOUT_MS", 30000)

TARGET_MAX_PAGES = env_limit("RR_TARGET_MAX_PAGES", 10_000)
TARGET_MAX_DEPTH = env_limit("RR_TARGET_MAX_DEPTH", 50)

OSINT_GRAPH_MAX_ENTITIES = env_limit("RR_OSINT_GRAPH_MAX_ENTITIES", 1_000)
OSINT_GRAPH_MAX_RELATIONS = env_limit("RR_OSINT_GRAPH_MAX_RELATIONS", 2_000)
OSINT_GRAPH_MAX_METADATA_KEYS = env_limit("RR_OSINT_GRAPH_MAX_METADATA_KEYS", 100)
OSINT_GRAPH_MAX_ENTITY_PROPERTY_KEYS = env_limit("RR_OSINT_GRAPH_MAX_ENTITY_PROPERTY_KEYS", 100)
OSINT_GRAPH_MAX_PROVENANCE_DEPTH = env_limit("RR_OSINT_GRAPH_MAX_PROVENANCE_DEPTH", 3)
OSINT_GRAPH_MAX_TEXT_LENGTH = env_limit("RR_OSINT_GRAPH_MAX_TEXT_LENGTH", 1000)
OSINT_GRAPH_MAX_IDENTITY_LENGTH = env_limit("RR_OSINT_GRAPH_MAX_IDENTITY_LENGTH", 2048)
OSINT_GRAPH_MAX_NESTED_LIST = env_limit("RR_OSINT_GRAPH_MAX_NESTED_LIST", 50)
OSINT_GRAPH_MAX_OBJECT_KEYS = env_limit("RR_OSINT_GRAPH_MAX_OBJECT_KEYS", 50)

CHAT_CONTEXT_HISTORY_LIMIT = env_limit("RR_CHAT_CONTEXT_HISTORY_LIMIT", 20)
CHAT_CONTEXT_TRAFFIC_LIMIT = env_limit("RR_CHAT_CONTEXT_TRAFFIC_LIMIT", 40)
CHAT_CONTEXT_BODY_LIMIT = env_limit("RR_CHAT_CONTEXT_BODY_LIMIT", 4000)
CHAT_MESSAGE_LIMIT = env_limit("RR_CHAT_MESSAGE_LIMIT", 12000)
CHAT_MESSAGES_LIMIT = env_limit("RR_CHAT_MESSAGES_LIMIT", 24)
CHAT_TOTAL_CONTEXT_LIMIT = env_limit("RR_CHAT_TOTAL_CONTEXT_LIMIT", 120000)
CHAT_PROJECT_CONTEXT_LIMIT = env_limit("RR_CHAT_PROJECT_CONTEXT_LIMIT", 60000)
CHAT_REQUEST_LIMIT = env_limit("RR_CHAT_REQUEST_LIMIT", 1_000_000)

HISTORY_LIST_LIMIT = env_limit("RR_HISTORY_LIST_LIMIT", 200)
WORKFLOW_LIST_LIMIT = env_limit("RR_WORKFLOW_LIST_LIMIT", 200)
WORKFLOW_RUN_LIST_LIMIT = env_limit("RR_WORKFLOW_RUN_LIST_LIMIT", 200)
OSINT_GRAPH_REQUEST_LIMIT = env_limit("RR_OSINT_GRAPH_REQUEST_LIMIT", 2_000_000)
OSINT_TRANSFORM_REQUEST_LIMIT = env_limit("RR_OSINT_TRANSFORM_REQUEST_LIMIT", 2_000_000)
ROUTE_CHECK_MAX_TIMEOUT_MS = env_limit("RR_ROUTE_CHECK_MAX_TIMEOUT_MS", 60000)
OAST_MAX_POLL_INTERVAL_SEC = env_limit("RR_OAST_MAX_POLL_INTERVAL_SEC", 60)
OAST_MAX_TIMEOUT_SEC = env_limit("RR_OAST_MAX_TIMEOUT_SEC", 300)

PROJECT_MAX_TECH_STACK_KEYS = env_limit("RR_PROJECT_MAX_TECH_STACK_KEYS", 100)
PROJECT_MAX_NOTES_LENGTH = env_limit("RR_PROJECT_MAX_NOTES_LENGTH", 20_000)
PROJECT_MAX_ENDPOINTS = env_limit("RR_PROJECT_MAX_ENDPOINTS", 200)
PROJECT_MAX_FINDINGS = env_limit("RR_PROJECT_MAX_FINDINGS", 100)
PROJECT_MAX_WORKFLOWS = env_limit("RR_PROJECT_MAX_WORKFLOWS", 50)
PROJECT_MAX_TARGET_JOBS = env_limit("RR_PROJECT_MAX_TARGET_JOBS", 50)
PROJECT_MAX_SECRET_REFERENCES = env_limit("RR_PROJECT_MAX_SECRET_REFERENCES", 50)
PROJECT_MAX_USER_QUERY_LENGTH = env_limit("RR_PROJECT_MAX_USER_QUERY_LENGTH", 12_000)
PROJECT_MAX_NESTED_DEPTH = env_limit("RR_PROJECT_MAX_NESTED_DEPTH", 3)
PROJECT_MAX_LIST_ITEMS = env_limit("RR_PROJECT_MAX_LIST_ITEMS", 50)
PROJECT_MAX_OBJECT_KEYS = env_limit("RR_PROJECT_MAX_OBJECT_KEYS", 50)
PROJECT_MAX_CONTEXT_VALUE_LENGTH = env_limit("RR_PROJECT_MAX_CONTEXT_VALUE_LENGTH", 500)
