"""Built-in, local workflow-template catalog for the Automation editor.

The catalog is intentionally data-only.  Importing a template still goes
through the normal workflow validator and confirmation flow; this module does
not execute network traffic or create active jobs by itself.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any


TEMPLATE_SCHEMA = "requestrider.workflow-template/v1"


def _connection(source: str, target: str, source_handle: str = "main") -> dict[str, str]:
    return {
        "source": source,
        "target": target,
        "source_handle": source_handle,
        "target_handle": "main",
    }


def _template(
    template_id: str,
    title: str,
    category: str,
    description: str,
    tags: list[str],
    risk_level: str,
    execution: str,
    estimated_execution_time_sec: int,
    nodes: list[dict[str, Any]],
    connections: list[dict[str, str]],
    required_variables: list[dict[str, Any]] | None = None,
    *,
    ai_enhanced: bool = False,
    requires_oast: bool = False,
    requires_confirmation: bool = False,
) -> dict[str, Any]:
    if requires_confirmation:
        for node in nodes:
            if node.get("type") == "manual_trigger":
                node.setdefault("params", {})["__requires_confirmation"] = True
    return {
        "$schema": TEMPLATE_SCHEMA,
        "template_id": template_id,
        "version": "1.0.0",
        "meta": {
            "title": title,
            "category": category,
            "author": "Request Rider Official",
            "risk_level": risk_level,
            "execution": execution,
            "tags": tags,
            "description": description,
            "estimated_execution_time_sec": estimated_execution_time_sec,
            "requires_oast": requires_oast,
            "ai_enhanced": ai_enhanced,
            "requires_confirmation": requires_confirmation,
        },
        "required_variables": required_variables or [],
        "workflow": {
            "name": title,
            "description": description,
            "project_id": None,
            "nodes": nodes,
            "connections": connections,
        },
    }


def _target_variable() -> list[dict[str, Any]]:
    return [{
        "key": "target_url",
        "label": "Target URL",
        "type": "url",
        "default": "",
        "required": True,
        "placeholder": "https://authorized.example.test/",
    }]


BUILTIN_TEMPLATES: list[dict[str, Any]] = [
    _template(
        "logic-baseline",
        "Logic graph baseline",
        "compliance_devsecops",
        "Перевіряє базову послідовність Condition → Merge → Output без активного трафіку.",
        ["Logic", "Condition", "Merge", "Smoke"],
        "info",
        "passive",
        5,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "set", "type": "set", "name": "Set values", "position": {"x": 320, "y": 100}, "params": {"values": {"status": "ready", "answer": 42}}},
            {"id": "condition", "type": "condition", "name": "Condition", "position": {"x": 560, "y": 100}, "params": {"field": "status", "operator": "equals", "value": "ready"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "Logic result", "format": "json"}},
        ],
        [_connection("trigger", "set"), _connection("set", "condition"), _connection("condition", "output", "true")],
    ),
    _template(
        "response-diff",
        "Response diff baseline",
        "compliance_devsecops",
        "Повторює один authorized URL і порівнює відповідь із еталонним значенням.",
        ["Repeater", "Comparer", "Regression"],
        "medium",
        "interactive",
        20,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "url": "{{target_url}}", "headers": {}, "body": "", "delay_ms": 150}},
            {"id": "comparer", "type": "comparer", "name": "Comparer", "position": {"x": 560, "y": 100}, "params": {"mode": "words", "left": "baseline", "right": "baseline"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "Response diff", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "comparer"), _connection("comparer", "output")],
        _target_variable(),
    ),
    _template(
        "recon-readonly",
        "Read-only perimeter baseline",
        "recon_asset_discovery",
        "Картує authorized target, виконує OSINT і Scanner без fuzzing та state-changing actions.",
        ["Target", "OSINT", "Scanner", "Read-only"],
        "low",
        "passive",
        60,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "target", "type": "target", "name": "Target map", "position": {"x": 320, "y": 100}, "params": {"url": "{{target_url}}", "engine": "static", "max_pages": 0, "max_depth": -1, "delay_ms": 250, "same_origin": True}},
            {"id": "osint", "type": "osint", "name": "OSINT", "position": {"x": 560, "y": 100}, "params": {"url": "{{target_url}}", "waf_check": False}},
            {"id": "scanner", "type": "scanner", "name": "Scanner", "position": {"x": 800, "y": 100}, "params": {"url": "{{target_url}}", "profile": "security_headers"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 1040, "y": 100}, "params": {"label": "Perimeter baseline", "format": "json"}},
        ],
        [_connection("trigger", "target"), _connection("target", "osint"), _connection("osint", "scanner"), _connection("scanner", "output")],
        _target_variable(),
    ),
    _template(
        "api-condition",
        "API status triage",
        "api_microservices",
        "Перевіряє authorized API endpoint і передає результат у Condition та Output.",
        ["API", "Status", "Condition", "Triage"],
        "medium",
        "interactive",
        25,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "url": "{{target_url}}", "headers": {}, "body": "", "delay_ms": 200}},
            {"id": "condition", "type": "condition", "name": "Condition", "position": {"x": 560, "y": 100}, "params": {"field": "response.status", "operator": "greater_than", "value": "399"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "API status triage", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "condition"), _connection("condition", "output", "true")],
        _target_variable(),
    ),
    _template(
        "js-ai-triage",
        "JS evidence to AI triage",
        "ai_llm_security",
        "Передає результат Target/Decoder AI-аналітику без автоматичного запуску активної атаки.",
        ["Target", "Decoder", "AI", "Evidence"],
        "low",
        "passive",
        45,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "target", "type": "target", "name": "Target map", "position": {"x": 300, "y": 100}, "params": {"url": "{{target_url}}", "engine": "static", "max_pages": 0, "max_depth": -1, "delay_ms": 250, "same_origin": True}},
            {"id": "decoder", "type": "decoder", "name": "Decoder", "position": {"x": 520, "y": 100}, "params": {"operation": "jsonPretty"}},
            {"id": "ai", "type": "ai_agent", "name": "AI Agent", "position": {"x": 740, "y": 100}, "params": {"prompt": "Analyze the attached evidence. Separate facts, hypotheses, and unknowns.", "provider": "ollama", "endpoint": "", "model": ""}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 960, "y": 100}, "params": {"label": "AI evidence report", "format": "markdown"}},
        ],
        [_connection("trigger", "target"), _connection("target", "decoder"), _connection("decoder", "ai"), _connection("ai", "output")],
        _target_variable(),
        ai_enhanced=True,
    ),
    _template(
        "intruder-triage",
        "Intruder anomaly triage",
        "fuzzing_injection",
        "Запускає dictionary fuzzing і передає результат AI; запуск потребує explicit confirmation.",
        ["Intruder", "Condition", "AI", "Fuzzing"],
        "high",
        "active",
        90,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "intruder", "type": "intruder", "name": "Intruder", "position": {"x": 320, "y": 100}, "params": {"base_request": {"method": "GET", "url": "{{target_url}}", "headers": {}, "body": ""}, "mode": "sniper", "payloads": [["baseline"]], "transformations": [], "delay_ms": 200, "concurrency": 1}},
            {"id": "condition", "type": "condition", "name": "Condition", "position": {"x": 560, "y": 100}, "params": {"field": "status", "operator": "greater_than", "value": "399"}},
            {"id": "ai", "type": "ai_agent", "name": "AI Agent", "position": {"x": 800, "y": 100}, "params": {"prompt": "Review the Intruder result and classify only observable evidence.", "provider": "ollama", "endpoint": "", "model": ""}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 1040, "y": 100}, "params": {"label": "Fuzzing triage", "format": "json"}},
        ],
        [_connection("trigger", "intruder"), _connection("intruder", "condition"), _connection("condition", "ai", "true"), _connection("ai", "output")],
        _target_variable(),
        ai_enhanced=True,
        requires_confirmation=True,
    ),
    _template(
        "browser-review",
        "Browser navigation review",
        "recon_asset_discovery",
        "Виконує browser-driven navigation без form fill/click actions; browser action залишається підтвердженням.",
        ["Target", "Browser", "Evidence", "Navigation"],
        "high",
        "interactive",
        90,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "target", "type": "target_browser", "name": "Browser Target", "position": {"x": 340, "y": 100}, "params": {"url": "{{target_url}}", "browser": "firefox", "mode": "navigation", "max_pages": 0, "max_depth": -1, "delay_ms": 300, "same_origin": True, "actions": [], "allow_state_changing_actions": False}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 600, "y": 100}, "params": {"label": "Browser evidence", "format": "json"}},
        ],
        [_connection("trigger", "target"), _connection("target", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "bounded-burst-review",
        "Parallel request review",
        "business_logic",
        "Надсилає parallel burst і порівнює результати без raw Last-Byte sync.",
        ["Repeater", "Burst", "Comparer", "Business Logic"],
        "high",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "burst", "type": "repeater_burst", "name": "Repeater Burst", "position": {"x": 340, "y": 100}, "params": {"method": "GET", "url": "{{target_url}}", "headers": {}, "iterations": 3, "concurrency": 2, "delay_ms": 100, "timeout_ms": 5000}},
            {"id": "comparer", "type": "comparer", "name": "Comparer", "position": {"x": 600, "y": 100}, "params": {"mode": "words", "left": "baseline", "right": "baseline"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 860, "y": 100}, "params": {"label": "Burst report", "format": "json"}},
        ],
        [_connection("trigger", "burst"), _connection("burst", "comparer"), _connection("comparer", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "last-byte-sync-review",
        "Last-Byte Sync timing review",
        "business_logic",
        "Експериментальний raw HTTP/1.1 POST із затримкою фінального байта; лише manual із явними параметрами, без Project URL-політики.",
        ["Last-Byte", "TCP/TLS", "Timing", "Manual"],
        "critical",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "last_byte", "type": "last_byte_sync", "name": "Last-Byte Sync", "position": {"x": 340, "y": 100}, "params": {"method": "POST", "url": "{{target_url}}", "headers": {"Content-Type": "application/json"}, "body": "{\"canary\":\"requestrider\"}", "iterations": 3, "concurrency": 1, "delay_ms": 250, "hold_ms": 100, "timeout_ms": 5000}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 600, "y": 100}, "params": {"label": "Last-Byte timing evidence", "format": "json"}},
        ],
        [_connection("trigger", "last_byte"), _connection("last_byte", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "oast-local-evidence",
        "Local OAST evidence chain",
        "oast_security",
        "Реєструє local OAST listener, передає payload URL у Repeater і збирає callback evidence.",
        ["OAST", "Repeater", "Evidence", "Callback"],
        "high",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "listener", "type": "oast_listener", "name": "OAST Listener", "position": {"x": 300, "y": 100}, "params": {"server_url": "{{oast_server_url}}", "listener_id": "", "poll_interval_sec": 1, "timeout_sec": 15, "capture_protocols": ["http"]}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 540, "y": 100}, "params": {"method": "GET", "url": "{{payload_url}}", "headers": {}, "body": "", "delay_ms": 0}},
            {"id": "collect", "type": "oast_collect", "name": "OAST Collect", "position": {"x": 780, "y": 100}, "params": {"poll_interval_sec": 1, "timeout_sec": 20}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 1020, "y": 100}, "params": {"label": "OAST evidence", "format": "json"}},
        ],
        [_connection("trigger", "listener"), _connection("listener", "repeater"), _connection("repeater", "collect"), _connection("collect", "output")],
        [{"key": "oast_server_url", "label": "Local OAST provider URL", "type": "url", "default": "http://127.0.0.1:8766", "required": True}],
        requires_confirmation=True,
    ),
    _template(
        "read-only-api-headers",
        "Read-only API headers baseline",
        "api_microservices",
        "Перевіряє один authorized GET endpoint і security headers без fuzzing та зміни стану.",
        ["API", "Headers", "Read-only", "Baseline"],
        "low",
        "passive",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "url": "{{target_url}}", "headers": {}, "body": "", "delay_ms": 200}},
            {"id": "scanner", "type": "scanner", "name": "Scanner", "position": {"x": 560, "y": 100}, "params": {"url": "{{target_url}}", "profile": "security_headers"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "API headers baseline", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "scanner"), _connection("scanner", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "js-asset-inventory",
        "JavaScript asset inventory",
        "recon_asset_discovery",
        "Збирає static asset map і нормалізує JSON evidence для подальшого огляду.",
        ["Target", "JavaScript", "Assets", "Read-only"],
        "low",
        "passive",
        45,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "target", "type": "target", "name": "Target map", "position": {"x": 320, "y": 100}, "params": {"url": "{{target_url}}", "engine": "static", "max_pages": 0, "max_depth": -1, "delay_ms": 250, "same_origin": True}},
            {"id": "decoder", "type": "decoder", "name": "Decoder", "position": {"x": 560, "y": 100}, "params": {"operation": "jsonPretty"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "JavaScript asset inventory", "format": "json"}},
        ],
        [_connection("trigger", "target"), _connection("target", "decoder"), _connection("decoder", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "debug-surface-readonly",
        "Read-only debug surface check",
        "recon_asset_discovery",
        "Перевіряє обмежений список стандартних debug/docs paths тільки методом GET.",
        ["Recon", "Debug", "Read-only", "Evidence"],
        "medium",
        "passive",
        40,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "urls": ["{{target_url}}/.git/HEAD", "{{target_url}}/actuator/health", "{{target_url}}/swagger-ui.html", "{{target_url}}/openapi.json"], "headers": {}, "body": "", "delay_ms": 200}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 560, "y": 100}, "params": {"label": "Debug surface evidence", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "schema-endpoint-discovery",
        "Schema endpoint discovery",
        "api_microservices",
        "Збирає лише read-only schema/document endpoints і передає їх у evidence output.",
        ["API", "OpenAPI", "GraphQL", "Discovery"],
        "low",
        "passive",
        35,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "urls": ["{{target_url}}/openapi.json", "{{target_url}}/swagger.json", "{{target_url}}/api-docs", "{{target_url}}/graphql"], "headers": {}, "body": "", "delay_ms": 200}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 560, "y": 100}, "params": {"label": "Schema endpoint evidence", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "perimeter-asset-inventory",
        "Perimeter asset inventory",
        "recon_asset_discovery",
        "Збирає passive target map і OSINT evidence без fuzzing, browser actions та OAST.",
        ["Recon", "Target", "OSINT", "Inventory"],
        "low",
        "passive",
        50,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "target", "type": "target", "name": "Target map", "position": {"x": 320, "y": 100}, "params": {"url": "{{target_url}}", "engine": "static", "max_pages": 0, "max_depth": -1, "delay_ms": 250, "same_origin": True}},
            {"id": "osint", "type": "osint", "name": "OSINT", "position": {"x": 560, "y": 100}, "params": {"url": "{{target_url}}", "waf_check": False}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "Perimeter asset inventory", "format": "json"}},
        ],
        [_connection("trigger", "target"), _connection("target", "osint"), _connection("osint", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "request-evidence-ai-triage",
        "Request evidence to AI triage",
        "ai_llm_security",
        "Передає один authorized request/response AI для advisory triage без активних дій.",
        ["Evidence", "AI", "Triage", "Advisory"],
        "low",
        "interactive",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "url": "{{target_url}}", "headers": {}, "body": "", "delay_ms": 0}},
            {"id": "ai", "type": "ai_agent", "name": "AI Agent", "position": {"x": 560, "y": 100}, "params": {"prompt": "Analyze only the attached response evidence. Separate facts, hypotheses, and unknowns. Do not recommend or execute external actions.", "provider": "ollama", "endpoint": "", "model": ""}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "Advisory evidence triage", "format": "markdown"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "ai"), _connection("ai", "output")],
        _target_variable(),
        ai_enhanced=True,
        requires_confirmation=True,
    ),
    _template(
        "bola-idor-differential",
        "BOLA/IDOR differential evidence",
        "business_logic",
        "Порівнює два authorized fixture records із різними object IDs; не змінює стан і не використовує реальні credentials.",
        ["BOLA", "IDOR", "Differential", "Manual"],
        "high",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "requests": [{"url": "{{target_url}}?fixture_id=owned-canary", "headers": {"X-Fixture-Owner": "alpha"}}, {"url": "{{target_url}}?fixture_id=foreign-canary", "headers": {"X-Fixture-Owner": "alpha"}}], "body": "", "delay_ms": 0}},
            {"id": "comparer", "type": "comparer", "name": "Comparer", "position": {"x": 560, "y": 100}, "params": {"mode": "words", "left": "baseline", "right": "baseline"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "BOLA/IDOR differential", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "comparer"), _connection("comparer", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "race-condition-observation",
        "Race-condition timing observation",
        "business_logic",
        "Виконує лише parallel GET спостереження з fixture таймінгом; не надсилає concurrent state-changing operation.",
        ["Race", "Timing", "Parallel", "Fixture"],
        "high",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "burst", "type": "repeater_burst", "name": "Repeater Burst", "position": {"x": 340, "y": 100}, "params": {"method": "GET", "url": "{{target_url}}/api/race?fixture_race=canary", "headers": {"X-Fixture-Canary": "race"}, "iterations": 4, "concurrency": 2, "delay_ms": 0, "timeout_ms": 2000}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 600, "y": 100}, "params": {"label": "Race timing observations", "format": "json"}},
        ],
        [_connection("trigger", "burst"), _connection("burst", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "waf-rule-differential",
        "WAF rule differential",
        "fuzzing_injection",
        "Порівнює baseline та harmless canary header/path evidence; не містить bypass payloads і не змінює target state.",
        ["WAF", "Differential", "Canary", "Manual"],
        "high",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "requests": [{"url": "{{target_url}}?waf_case=baseline", "headers": {}}, {"url": "{{target_url}}?waf_case=canary", "headers": {"X-Safe-Canary": "requestrider"}}], "body": "", "delay_ms": 0}},
            {"id": "comparer", "type": "comparer", "name": "Comparer", "position": {"x": 560, "y": 100}, "params": {"mode": "words", "left": "baseline", "right": "baseline"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "WAF differential evidence", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "comparer"), _connection("comparer", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "jwt-claim-mutation-differential",
        "JWT claim mutation differential",
        "auth_sessions",
        "Перевіряє decoder/response differential для synthetic unsigned JWT claims; не приймає справжні токени й не змінює claims.",
        ["JWT", "Claims", "Differential", "Synthetic"],
        "high",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "requests": [{"url": "{{target_url}}?jwt=eyJhbGciOiJub25lIn0.eyJzdWIiOiJmaXh0dXJlIn0.signature", "headers": {"Authorization": "Bearer synthetic-canary"}}, {"url": "{{target_url}}?jwt=eyJhbGciOiJub25lIn0.eyJzdWIiOiJmaXh0dXJlIiwicm9sZSI6ImNhbmFyeSJ9.signature", "headers": {"Authorization": "Bearer synthetic-canary"}}], "body": "", "delay_ms": 0}},
            {"id": "comparer", "type": "comparer", "name": "Comparer", "position": {"x": 560, "y": 100}, "params": {"mode": "words", "left": "baseline", "right": "baseline"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 800, "y": 100}, "params": {"label": "Synthetic JWT evidence", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "comparer"), _connection("comparer", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "xxe-oast-canary",
        "XXE/OAST local canary chain",
        "oast_security",
        "Відправляє XML canary з local OAST entity лише через authorized loopback fixture; callback зберігається як evidence.",
        ["XXE", "OAST", "Canary", "Local Fixture"],
        "critical",
        "active",
        30,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "listener", "type": "oast_listener", "name": "OAST Listener", "position": {"x": 300, "y": 100}, "params": {"server_url": "{{oast_server_url}}", "listener_id": "", "poll_interval_sec": 1, "timeout_sec": 15, "capture_protocols": ["http"]}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 540, "y": 100}, "params": {"method": "POST", "url": "{{target_url}}", "headers": {"Content-Type": "application/xml"}, "body": '<?xml version="1.0"?><!DOCTYPE canary [<!ENTITY xxe SYSTEM "{{payload_url}}">]><canary>&xxe;</canary>', "delay_ms": 0}},
            {"id": "collect", "type": "oast_collect", "name": "OAST Collect", "position": {"x": 780, "y": 100}, "params": {"poll_interval_sec": 1, "timeout_sec": 20}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 1020, "y": 100}, "params": {"label": "XXE/OAST canary evidence", "format": "json"}},
        ],
        [_connection("trigger", "listener"), _connection("listener", "repeater"), _connection("repeater", "collect"), _connection("collect", "output")],
        [
            {"key": "target_url", "label": "Authorized XML fixture URL", "type": "url", "default": "", "required": True, "placeholder": "http://127.0.0.1:fixture/xml"},
            {"key": "oast_server_url", "label": "Local OAST provider URL", "type": "url", "default": "http://127.0.0.1:8766", "required": True},
        ],
        requires_oast=True,
        requires_confirmation=True,
    ),
    _template(
        "ci-cd-exposure-review",
        "CI/CD exposure review",
        "compliance_devsecops",
        "Read-only перевірка стандартних CI/CD manifest paths без застосування конфігурації, build або deploy.",
        ["CI/CD", "Exposure", "Read-only", "Manifests"],
        "medium",
        "active",
        25,
        [
            {"id": "trigger", "type": "manual_trigger", "name": "Manual trigger", "position": {"x": 80, "y": 100}, "params": {}},
            {"id": "repeater", "type": "repeater", "name": "Repeater", "position": {"x": 320, "y": 100}, "params": {"method": "GET", "urls": ["{{target_url}}/.github/workflows/ci.yml", "{{target_url}}/.gitlab-ci.yml", "{{target_url}}/Jenkinsfile", "{{target_url}}/.circleci/config.yml"], "headers": {}, "body": "", "delay_ms": 100}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 560, "y": 100}, "params": {"label": "CI/CD exposure evidence", "format": "json"}},
        ],
        [_connection("trigger", "repeater"), _connection("repeater", "output")],
        _target_variable(),
        requires_confirmation=True,
    ),
    _template(
        "scheduled-readonly",
        "Scheduled read-only scan",
        "compliance_devsecops",
        "Запускає Scanner за cron і зберігає результат без fuzzing.",
        ["Schedule", "Scanner", "Monitoring", "Read-only"],
        "low",
        "passive",
        30,
        [
            {"id": "schedule", "type": "schedule_trigger", "name": "Schedule trigger", "position": {"x": 80, "y": 100}, "params": {"cron": "0 3 * * 1"}},
            {"id": "scanner", "type": "scanner", "name": "Scanner", "position": {"x": 340, "y": 100}, "params": {"url": "{{target_url}}", "profile": "security_headers"}},
            {"id": "output", "type": "output", "name": "Output", "position": {"x": 600, "y": 100}, "params": {"label": "Scheduled scan", "format": "json"}},
        ],
        [_connection("schedule", "scanner"), _connection("scanner", "output")],
        _target_variable(),
    ),
]


def list_templates() -> list[dict[str, Any]]:
    """Return a detached catalog so callers cannot mutate the registry."""

    return deepcopy(BUILTIN_TEMPLATES)
