# Generated by Django 5.2.17 on 2026-09-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_trafficrecord_source_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficrecord',
            name='source',
            field=models.CharField(choices=[('repeater', 'Repeater'), ('intruder', 'Intruder'), ('proxy', 'Proxy'), ('route-check', 'Route check')], default='repeater', max_length=20),
        ),
    ]
