# Generated by Django 5.2.17 on 2026-09-22 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_alter_trafficrecord_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('target', models.URLField(blank=True, default='', max_length=2048)),
                ('environment', models.CharField(blank=True, default='', max_length=160)),
                ('route_profile', models.CharField(blank=True, default='', max_length=160)),
                ('metadata', models.JSONField(default=dict)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trafficsession',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='intruderattack',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intruder_attacks', to='lab.project'),
        ),
        migrations.AddField(
            model_name='trafficrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_records', to='lab.project'),
        ),
        migrations.AddField(
            model_name='trafficsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_sessions', to='lab.project'),
        ),
    ]
