# Generated by Django 5.2.17 on 2026-09-22 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_project_trafficsession_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('verification_status', models.CharField(default='unverified', max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('false_positive', 'False positive'), ('accepted_risk', 'Accepted risk'), ('fixed', 'Fixed')], default='new', max_length=20)),
                ('target', models.URLField(blank=True, default='', max_length=2048)),
                ('source', models.CharField(default='scanner', max_length=40)),
                ('evidence_before', models.JSONField(default=dict)),
                ('evidence_after', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='lab.project')),
            ],
        ),
    ]
