# Generated by Django 5.2.17 on 2026-09-22 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=128, unique=True)),
                ('engine_kind', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(default='running', max_length=30)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_jobs', to='lab.project')),
            ],
        ),
    ]
