# Generated by Django 5.2.17 on 2026-09-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_project_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='ProjectSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_type', models.CharField(choices=[('jwt', 'JWT'), ('api_key', 'API key'), ('password', 'Password'), ('leak', 'Leak reference')], default='api_key', max_length=20)),
                ('key_name', models.CharField(max_length=120)),
                ('value_ref', models.CharField(blank=True, default='', max_length=240)),
                ('source_url', models.URLField(blank=True, default='', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_references', to='lab.project')),
            ],
            options={
                'ordering': ['secret_type', 'key_name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value_ref', ''), ('value_ref__startswith', 'env:'), _connector='OR'), name='project_secret_value_ref_env_only')],
            },
        ),
    ]
