# Generated by Django 5.2.17 on 2026-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0028_project_knowledge_base'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectsecret',
            name='project_secret_value_ref_env_only',
        ),
        migrations.AddConstraint(
            model_name='projectsecret',
            constraint=models.CheckConstraint(condition=models.Q(('value_ref', ''), ('value_ref__regex', '^env:[A-Za-z_][A-Za-z0-9_]*$'), _connector='OR'), name='project_secret_value_ref_env_only'),
        ),
    ]
