# Generated by Django 5.2.17 on 2026-09-24 12:22

import django.db.models.deletion
import lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0029_tighten_project_secret_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrecord',
            name='scope_status',
            field=models.CharField(choices=[('unscoped', 'Unscoped'), ('in_scope', 'In scope'), ('out_of_scope', 'Out of scope'), ('invalid_context', 'Invalid capture context')], default='unscoped', max_length=20),
        ),
        migrations.CreateModel(
            name='TrafficCaptureContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('token', models.CharField(default=lab.models.generate_capture_context_token, editable=False, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_capture_contexts', to='lab.project')),
            ],
        ),
        migrations.AddField(
            model_name='targetjob',
            name='capture_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_jobs', to='lab.trafficcapturecontext'),
        ),
        migrations.AddField(
            model_name='trafficrecord',
            name='capture_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_records', to='lab.trafficcapturecontext'),
        ),
    ]
