# Generated by Django 5.2.17 on 2026-09-24 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0030_traffic_capture_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('current', 'Current'), ('archived', 'Archived')], default='current', max_length=20)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_graphs', to='lab.project')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OsintEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain'), ('ip', 'IP'), ('cidr', 'CIDR'), ('url', 'URL'), ('email', 'Email'), ('username', 'Username'), ('asn', 'ASN'), ('certificate', 'Certificate'), ('technology', 'Technology'), ('port', 'Port'), ('cloud_asset', 'Cloud asset')], max_length=32)),
                ('identity', models.CharField(max_length=2048)),
                ('display_value', models.CharField(blank=True, default='', max_length=512)),
                ('properties', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_entities', to='lab.project')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='lab.osintgraph')),
            ],
            options={
                'ordering': ['entity_type', 'identity'],
            },
        ),
        migrations.CreateModel(
            name='OsintRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=64)),
                ('properties', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='lab.osintgraph')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osint_relations', to='lab.project')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='lab.osintentity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='lab.osintentity')),
            ],
            options={
                'ordering': ['relation_type', 'source_entity', 'target_entity'],
            },
        ),
        migrations.AddConstraint(
            model_name='osintgraph',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='osint_graph_project_version_unique'),
        ),
        migrations.AddIndex(
            model_name='osintentity',
            index=models.Index(fields=['project', 'entity_type'], name='lab_osinten_project_f1ad4a_idx'),
        ),
        migrations.AddIndex(
            model_name='osintentity',
            index=models.Index(fields=['graph', 'observed_at'], name='lab_osinten_graph_i_d13b02_idx'),
        ),
        migrations.AddConstraint(
            model_name='osintentity',
            constraint=models.UniqueConstraint(fields=('graph', 'entity_type', 'identity'), name='osint_entity_graph_type_identity_unique'),
        ),
        migrations.AddIndex(
            model_name='osintrelation',
            index=models.Index(fields=['project', 'relation_type'], name='lab_osintre_project_47402b_idx'),
        ),
        migrations.AddIndex(
            model_name='osintrelation',
            index=models.Index(fields=['graph', 'observed_at'], name='lab_osintre_graph_i_109acd_idx'),
        ),
        migrations.AddConstraint(
            model_name='osintrelation',
            constraint=models.UniqueConstraint(fields=('graph', 'relation_type', 'source_entity', 'target_entity'), name='osint_relation_graph_type_endpoints_unique'),
        ),
    ]
