# Generated by Django 5.2.17 on 2026-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0031_osint_entity_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='osintentity',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='osintgraph',
            name='name',
            field=models.CharField(default='OSINT graph', max_length=160),
        ),
        migrations.AddConstraint(
            model_name='osintentity',
            constraint=models.CheckConstraint(condition=models.Q(('risk_score__gte', 0), ('risk_score__lte', 100)), name='osint_entity_risk_score_0_100'),
        ),
    ]
