# Generated by Django 5.1 on 2025-01-01 00:00
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [("lab", "0034_remove_trafficsession")]

    operations = [
        migrations.CreateModel(
            name="ProjectEndpoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("method", models.CharField(max_length=16)),
                ("path", models.CharField(max_length=2048)),
                ("sample_url", models.URLField(blank=True, default="", max_length=2048)),
                ("statuses", models.JSONField(default=list)),
                ("parameters", models.JSONField(default=list)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="endpoints", to="lab.project")),
            ],
            options={
                "ordering": ["path", "method"],
                "indexes": [models.Index(fields=["project", "path"], name="lab_project_project_53f274_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("project", "method", "path"), name="project_endpoint_method_path_unique"),
                ],
            },
        ),
    ]
