# Generated by Django 5.2
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lab", "0035_projectendpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="intruderattack",
            name="engine_attack_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
    ]
