# Generated by Django 5.2.17 on 2026-09-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0036_intruderattack_engine_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finding',
        ),
    ]
