# Generated by Django 5.2.17 on 2026-09-25 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0037_delete_finding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('builtin', 'Builtin'), ('templates', 'Templates'), ('nuclei', 'Nuclei')], default='builtin', max_length=20)),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('summary', models.JSONField(default=dict)),
                ('findings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanner_runs', to='lab.project')),
            ],
        ),
    ]
