# Generated by Django 5.2.17 on 2026-09-25 08:56

import lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0038_scannerrun'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='osintentity',
            name='osint_entity_risk_score_0_100',
        ),
        migrations.RemoveConstraint(
            model_name='projectsecret',
            name='project_secret_value_ref_env_only',
        ),
        migrations.AlterField(
            model_name='intruderattack',
            name='attack_type',
            field=models.TextField(choices=[('sniper', 'Sniper'), ('batteringRam', 'Battering Ram'), ('pitchfork', 'Pitchfork'), ('clusterBomb', 'Cluster Bomb')]),
        ),
        migrations.AlterField(
            model_name='intruderattack',
            name='engine_attack_id',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='intruderattack',
            name='name',
            field=models.TextField(default='Intruder attack'),
        ),
        migrations.AlterField(
            model_name='intruderattack',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='osintentity',
            name='display_value',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='osintentity',
            name='entity_type',
            field=models.TextField(choices=[('domain', 'Domain'), ('subdomain', 'Subdomain'), ('ip', 'IP'), ('cidr', 'CIDR'), ('url', 'URL'), ('email', 'Email'), ('username', 'Username'), ('asn', 'ASN'), ('certificate', 'Certificate'), ('technology', 'Technology'), ('port', 'Port'), ('cloud_asset', 'Cloud asset')]),
        ),
        migrations.AlterField(
            model_name='osintentity',
            name='identity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='osintentity',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='osintgraph',
            name='name',
            field=models.TextField(default='OSINT graph'),
        ),
        migrations.AlterField(
            model_name='osintgraph',
            name='source',
            field=models.TextField(default='manual'),
        ),
        migrations.AlterField(
            model_name='osintgraph',
            name='status',
            field=models.TextField(choices=[('current', 'Current'), ('archived', 'Archived')], default='current'),
        ),
        migrations.AlterField(
            model_name='osintrelation',
            name='relation_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='environment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='route_profile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='target',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectendpoint',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectendpoint',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectendpoint',
            name='sample_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectsecret',
            name='key_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projectsecret',
            name='secret_type',
            field=models.TextField(choices=[('jwt', 'JWT'), ('api_key', 'API key'), ('password', 'Password'), ('leak', 'Leak reference')], default='api_key'),
        ),
        migrations.AlterField(
            model_name='projectsecret',
            name='source_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectsecret',
            name='value_ref',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scannerrun',
            name='engine',
            field=models.TextField(choices=[('builtin', 'Builtin'), ('templates', 'Templates'), ('nuclei', 'Nuclei')], default='builtin'),
        ),
        migrations.AlterField(
            model_name='scannerrun',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='targetjob',
            name='engine_kind',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='targetjob',
            name='job_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='targetjob',
            name='status',
            field=models.TextField(default='running'),
        ),
        migrations.AlterField(
            model_name='targetjob',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trafficcapturecontext',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trafficcapturecontext',
            name='token',
            field=models.TextField(default=lab.models.generate_capture_context_token, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='host',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='request_body_encoding',
            field=models.TextField(default='utf8'),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='response_body_encoding',
            field=models.TextField(default='utf8'),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='response_content_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='scope_status',
            field=models.TextField(choices=[('unscoped', 'Unassigned'), ('project_linked', 'Project-linked'), ('in_scope', 'Legacy project-linked'), ('out_of_scope', 'Legacy scope metadata'), ('invalid_context', 'Invalid capture context')], default='unscoped'),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='source',
            field=models.TextField(choices=[('repeater', 'Repeater'), ('intruder', 'Intruder'), ('last-byte', 'Last-Byte Sync'), ('proxy', 'Proxy'), ('route-check', 'Route check')], default='repeater'),
        ),
        migrations.AlterField(
            model_name='trafficrecord',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.TextField(default='Workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='schedule',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='webhook_slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='current_node',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='mode',
            field=models.TextField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('webhook', 'Webhook')], default='manual'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.TextField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], default='queued'),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='trigger_node_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='trigger_type',
            field=models.TextField(default='manual'),
        ),
    ]
