# Generated by Django 5.2.17 on 2026-09-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0039_remove_osintentity_osint_entity_risk_score_0_100_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trafficrecord',
            index=models.Index(fields=['source', 'proxy_session', 'proxy_event_id'], name='lab_traffic_dedup_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficrecord',
            index=models.Index(fields=['source', 'timestamp'], name='lab_traffic_source_time_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficrecord',
            index=models.Index(fields=['project', 'timestamp'], name='lab_traffic_project_time_idx'),
        ),
    ]
