# Generated by Django 5.2.17 on 2026-09-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0041_trafficrecord_lab_traffic_recent_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetjob',
            name='ingested',
            field=models.BooleanField(default=False),
        ),
    ]
