# Generated by Django 5.2.17 on 2026-09-26 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0042_targetjob_ingested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
